### ISSUE TITLE
load_target_positions bug

### ISSUE THREAD

**Issue by ahanden** [BioinfoUNIBA/REDItools3#21]
From Michelle Eidelman:

> Dear Alessandro and Adriano,
> 
> I hope this email finds you well. 
> 
> I am reaching out for assistance with an issue I encountered while using REDItools3. Specifically, the program reports a problem with the load_target_positions method, which prevents the use of the -B flag for specifying BED files during the analyze mode.
> 
> Here is the command I used:
> 
>  
> 
>  
> 
> python -m reditools analyze -o ../output.txt -s 0 -a -C -r ../hg38.fa -q 30 -d -t 4 -B ../redions.bed ../input.bam"
> 
> The following error was generated:
> 
> Traceback (most recent call last):
>   File "/home/alu/eidelman/.conda/envs/Py3.10/lib/python3.10/site-packages/reditools/analyze.py", line 193, in run
>     rtools = setup_rtools(options)
>   File "/home/alu/eidelman/.conda/envs/Py3.10/lib/python3.10/site-packages/reditools/analyze.py", line 92, in setup_rtools
>     rtools.load_target_positions(options.bed_file)
> AttributeError: 'REDItools' object has no attribute 'load_target_positions'
> [ERROR] 'REDItools' object has no attribute 'load_target_positions'
> Traceback (most recent call last):
>   File "/home/alu/eidelman/.conda/envs/Py3.10/lib/python3.10/site-packages/reditools/analyze.py", line 193, in run
>     rtools = setup_rtools(options)
>   File "/home/alu/eidelman/.conda/envs/Py3.10/lib/python3.10/site-packages/reditools/analyze.py", line 92, in setup_rtools
>     rtools.load_target_positions(options.bed_file)
> AttributeError: 'REDItools' object has no attribute 'load_target_positions'
> [ERROR] 'REDItools' object has no attribute 'load_target_positions'
> Traceback (most recent call last):
>   File "/home/alu/eidelman/.conda/envs/Py3.10/lib/python3.10/site-packages/reditools/analyze.py", line 193, in run
>     rtools = setup_rtools(options)
>   File "/home/alu/eidelman/.conda/envs/Py3.10/lib/python3.10/site-packages/reditools/analyze.py", line 92, in setup_rtools
>     rtools.load_target_positions(options.bed_file)
> AttributeError: 'REDItools' object has no attribute 'load_target_positions'
> [ERROR] 'REDItools' object has no attribute 'load_target_positions'
> Traceback (most recent call last):
>   File "/home/alu/eidelman/.conda/envs/Py3.10/lib/python3.10/site-packages/reditools/analyze.py", line 193, in run
>     rtools = setup_rtools(options)
>   File "/home/alu/eidelman/.conda/envs/Py3.10/lib/python3.10/site-packages/reditools/analyze.py", line 92, in setup_rtools
>     rtools.load_target_positions(options.bed_file)
> AttributeError: 'REDItools' object has no attribute 'load_target_positions'
> [ERROR] 'REDItools' object has no attribute 'load_target_positions'
> 
> 
>  
> 
> To troubleshoot, I tested three types of input files of regions, each containing a single row: 
> 
> bed6: chr1    65564   65565   CDS     .       +
> bed3: chr1     65565    65566   
> 
> REDITools1 input format of regions: chr1     65566   +
>  
>  
> 
> I also have a question regarding strand information in REDItools2. My dataset is unstranded, so I used the -s 0 flag. However, my BED file includes strand annotations for specific regions. Despite this, the output from REDItools2 marks all regions as having an unknown strand (2), and the reference column consistently shows the reference plus strand (+), even for regions I annotated as being on the minus strand. This behavior differs from the previous version (REDItools1), where the strand was considered for each region, and the reference was complemented accordingly when necessary.
> 
> Could you clarify how strand information is processed in REDItools2/REDITools3? My goal is to analyze mismatches while accounting for homopolymeric regions and splice junctions across various genomic regions, where some are on the plus strand and others on the minus strand of the reference genome. How is this handled in REDItools2 and REDItools3?
> 
> 
> Thank you for your assistance, and please let me know if further details or additional examples are needed.

**Comment by ahanden** [comment]
I've found the problem and fixed it in the dev branch. I'll be releasing v3.3a this week which will include the fix.
